import { BusinessContext, PastCategorization, FewShotExample, RawTransaction } from './types'

export class ContextManager {
  private businessContext: Map<string, BusinessContext> = new Map()
  private pastCategorizations: Map<string, PastCategorization[]> = new Map()
  private fewShotExamples: Map<string, FewShotExample[]> = new Map()
  private maxExamplesPerUser: number = 50

  setBusinessContext(userId: string, context: BusinessContext): void {
    this.businessContext.set(userId, context)
  }

  getBusinessContext(userId: string): BusinessContext | undefined {
    return this.businessContext.get(userId)
  }

  addPastCategorization(userId: string, categorization: PastCategorization): void {
    const existing = this.pastCategorizations.get(userId) || []
    existing.push(categorization)
    
    // Keep only recent categorizations (last 100)
    if (existing.length > 100) {
      existing.splice(0, existing.length - 100)
    }
    
    this.pastCategorizations.set(userId, existing)
  }

  getPastCategorizations(userId: string): PastCategorization[] {
    return this.pastCategorizations.get(userId) || []
  }

  addFewShotExample(userId: string, example: FewShotExample): void {
    const existing = this.fewShotExamples.get(userId) || []
    existing.push(example)
    
    // Enforce max examples limit
    if (existing.length > this.maxExamplesPerUser) {
      // Remove oldest examples
      existing.splice(0, existing.length - this.maxExamplesPerUser)
    }
    
    this.fewShotExamples.set(userId, existing)
  }

  getFewShotExamples(userId: string): FewShotExample[] {
    return this.fewShotExamples.get(userId) || []
  }

  async learnFromCorrection(
    userId: string,
    transaction: RawTransaction,
    originalCategory: string,
    correctedCategory: string
  ): Promise<void> {
    // Add to past categorizations
    this.addPastCategorization(userId, {
      transaction,
      category: originalCategory as any,
      was_corrected: true,
      corrected_to: correctedCategory as any,
    })

    // Create a few-shot example (explanation will be generated by the agent)
    const example: FewShotExample = {
      transaction,
      category: correctedCategory as any,
      explanation: `User corrected from ${originalCategory} to ${correctedCategory}`,
    }
    
    this.addFewShotExample(userId, example)
  }

  getRelevantContext(
    userId: string,
    currentTransactions: RawTransaction[]
  ): {
    businessContext?: BusinessContext
    pastCategorizations: PastCategorization[]
    fewShotExamples: FewShotExample[]
  } {
    const businessContext = this.getBusinessContext(userId)
    const pastCategorizations = this.getPastCategorizations(userId)
    const fewShotExamples = this.getFewShotExamples(userId)

    // Filter few-shot examples to find relevant ones based on counterparty or amount patterns
    const relevantExamples = this.filterRelevantExamples(fewShotExamples, currentTransactions)

    return {
      businessContext,
      pastCategorizations,
      fewShotExamples: relevantExamples,
    }
  }

  private filterRelevantExamples(
    examples: FewShotExample[],
    currentTransactions: RawTransaction[]
  ): FewShotExample[] {
    if (examples.length === 0) return []

    const currentCounterparties = new Set(
      currentTransactions
        .map((t) => t.counterparty)
        .filter((c): c is string => !!c)
    )

    // Prioritize examples with matching counterparties
    const relevant = examples.filter((example) => {
      const exampleCounterparty = example.transaction.counterparty
      if (exampleCounterparty && currentCounterparties.has(exampleCounterparty)) {
        return true
      }
      return false
    })

    // If we have enough relevant examples, return them
    if (relevant.length >= 5) {
      return relevant.slice(0, 10)
    }

    // Otherwise, return a mix of relevant and recent examples
    const recent = examples.slice(-10)
    const combined = [...relevant, ...recent]
    
    // Remove duplicates
    const unique = combined.filter(
      (example, index, self) =>
        index === self.findIndex((e) => e.transaction.id === example.transaction.id)
    )

    return unique.slice(0, 15)
  }

  clearUserContext(userId: string): void {
    this.businessContext.delete(userId)
    this.pastCategorizations.delete(userId)
    this.fewShotExamples.delete(userId)
  }
}
